event:
  name: "Oscars 2026"
  id: oscars_2026
  sport: entertainment
  espn_league: ""

timing:
  start: "2026-03-15T17:00:00-06:00"
  end: "2026-03-15T23:00:00-06:00"
  poll_interval: 60

kalshi:
  series_tickers: [KXOSC, KXAWARD]
  search_keywords: [oscars, academy award, best picture, best actor, best actress]

risk:
  max_exposure: 200
  max_single_trade: 30
  circuit_breaker_loss: 50

odds:
  sport_key: ""
  bookmakers: []

sentiment:
  subreddits: [oscars, movies, entertainment]
  news_queries: ["oscars 2026", "academy awards", "best picture prediction"]
  teams: []

triggers: {}

espn:
  date: ""
  teams: []
